# -*- coding: utf-8 -*-
"""Get File counts inside Drive Folders.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nAR1pqeQchsP6GRlCiuZQBPK6vk2Wtsh
"""

import os
from collections import defaultdict
from google.colab import drive
drive.mount('/content/drive')
base_directory = '/content/drive/MyDrive/'

def count_files_by_extension(base_dir):
    folder_count = 0
    total_file_count = 0
    file_count_by_extension = defaultdict(int)
    file_count_by_folder = defaultdict(lambda: defaultdict(int))

    for root, dirs, files in os.walk(base_dir):
        folder_count += 1
        total_file_count += len(files)

        # Count files by extension
        for file in files:
            _, ext = os.path.splitext(file)
            ext = ext.lower()
            file_count_by_extension[ext] += 1
            file_count_by_folder[root][ext] += 1

    return folder_count, total_file_count, file_count_by_extension, file_count_by_folder

#Change this to your specific directory
base_directory = '/content/drive/MyDrive'

folder_count, total_file_count, file_count_by_extension, file_count_by_folder = count_files_by_extension(base_directory)

print(f'Total number of folders: {folder_count}')
print(f'Total number of files: {total_file_count}')
print('\nFile count by extension:')
for ext, count in file_count_by_extension.items():
    print(f'{ext}: {count}')

print('\nFile count by folder:')
for folder, counts in file_count_by_folder.items():
    print(f'\nFolder: {folder}')
    for ext, count in counts.items():
        print(f'  {ext}: {count}')